# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 987326b2a7f600f027c025a5d81eede2dfda5fd9bb6525a788bf868be2c2af44d5632737a52a53b3ffbc9f34252305f3bfc6a83b2b333a3ed325d2f0d2c7d99e

test:
  secret_key_base: 6610376b084d161dbbc439920dc214e1bce5e7dddac0537bfeda16a9c3be1b25024a0fc48b9a97c31e74a8f510f50c8d2e6eac8ec185f23d426d5444f4a45b00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
